cookie:
  key: "<secret-password>" # password for cookie
server:
  addr: "host:port"
  wto:  10s # write time out
  rto:  10s # read time out
logger:
  level:       "debug" # debug, info, warn, error
  server_path: "logs/..." # path to server log
  sqlite_path: "logs/..."
  mw_path:     "logs/..."
